package ai

// Role helps to distinguish between system-level prompts, user input and assistant responses.
type Role string

const (
	// RoleSystem is used for messages generated by the system to control or set context for the conversation.
	RoleSystem = "system"

	// RoleUser represents messages from the end user.
	RoleUser = "user"

	// RoleAssistant represents replies generated by the AI assistant.
	RoleAssistant = "assistant"
)

// Message models a single message in the conversation, tagged with its role and text content.
type Message struct {
	Role    Role   `json:"role"`
	Content string `json:"content"`
}
