package ai

import "fmt"

/********* Enums *********/

// Role helps to distinguish between system-level prompts, user input and assistant responses.
type Role string

const (
	// RoleSystem is used for messages generated by the system to control or set context for the conversation.
	RoleSystem Role = "system"
	// RoleUser represents messages from the end user.
	RoleUser Role = "user"
	// RoleAssistant represents replies generated by the AI assistant.
	RoleAssistant Role = "assistant"
)

func (r Role) String() string { return string(r) }

func (r Role) IsValid() bool {
	switch r {
	case RoleSystem, RoleUser, RoleAssistant:
		return true
	default:
		return false
	}
}

// Provider differentiates between different AI providers.
type Provider string

const (
	// ProviderOpenAI is used fot chat, tts, and transcription.
	ProviderOpenAI Provider = "openai"
	// ProviderAnthropic is used for chat.
	ProviderAnthropic Provider = "anthropic"
	// ProviderElevenLabs is used for tts.
	ProviderElevenLabs Provider = "elevenlabs"
)

func (p Provider) String() string { return string(p) }

func (p Provider) IsValid() bool {
	switch p {
	case ProviderOpenAI, ProviderAnthropic, ProviderElevenLabs:
		return true
	default:
		return false
	}
}

// Operation can be a chat, a text-to-speech (tts), or a speech-to-text (stt).
type Operation string

const (
	OpChatCompletion   Operation = "chat completion"
	OpTTSAudio         Operation = "text-to-speech audio"
	OpSTTTranscription Operation = "speech-to-text transcription"
)

func (o Operation) String() string { return string(o) }
func (o Operation) IsValid() bool {
	switch o {
	case OpChatCompletion, OpTTSAudio, OpSTTTranscription:
		return true
	default:
		return false
	}
}

/********* Errors *********/

// AIError reports an unsucessful AI operation, for a provider, with a useful message,
// and the wrapped error cause.
type AIError struct {
	Operation Operation
	Provider  Provider
	Message   string
	Wrapped   error
}

func (e *AIError) Error() string {
	if e.Wrapped != nil {
		return fmt.Sprintf("%s: %s: %s: %v", e.Operation, e.Provider, e.Message, e.Wrapped)
	}
	return fmt.Sprintf("%s[%s] error: %s", e.Operation, e.Provider, e.Message)
}

func (e *AIError) Unwrap() error { return e.Wrapped }

// NewAIError is a generic constructor for more specific error.
func NewAIError(op Operation, pvd Provider, msg string, err error) error {
	return &AIError{Operation: op, Provider: pvd, Message: msg, Wrapped: err}
}

// /NewChatError returns an unsuccessful chat completion.
func NewChatError(p Provider, msg string, err error) error {
	return NewAIError(OpChatCompletion, p, msg, err)
}

// NewTTSError returns an unsuccessful text-to-speech synthesis.
func NewTTSError(p Provider, msg string, err error) error {
	return NewAIError(OpTTSAudio, p, msg, err)
}

// NewSTTError returns an unsuccessful speech-to-text transcription.
func NewSTTError(p Provider, msg string, err error) error {
	return NewAIError(OpSTTTranscription, p, msg, err)
}

/********* Interfaces *********/

// Chat defines behaviors to perform a chat completion.
type Chat interface {
	SetSystem(instructions string) *Chat
	AddMessage(role Role, content string) *Chat
	Completion() (Completion, error)
}

// TTS defines behaviors to synthetize a text-to-speech audio.
type TTS interface {
	Audio() ([]byte, error)
}

// STT defines behaviors to perform a speech-to-text transcription.
type STT interface {
	Transcript() (Transcription, error)
}

/********* Common *********/

// Message models a single message in the conversation, tagged with its role and text content.
type Message struct {
	Role    Role   `json:"role"`
	Content string `json:"content"`
}

// Completion holds the result of chat completions for chat completion providers.
type Completion struct {
	ID        string                `json:"id,omitempty"`
	OpenAI    []OpenAICompletion    `json:"choices,omitempty"`
	Anthropic []AnthropicCompletion `json:"content,omitempty"`
}

// Content extracts the main text of the first choice, or returns empty
// if no content is available.
func (res Completion) Content() string {
	if len(res.OpenAI) > 0 && res.OpenAI[0].Message.Content != "" {
		return res.OpenAI[0].Message.Content
	}
	if len(res.Anthropic) > 0 && res.Anthropic[0].Content != "" {
		return res.Anthropic[0].Content
	}
	return ""
}

// Transcription holds the text after the transcription is done.
type Transcription struct {
	Text string `json:"text,omitempty"`
}

// Content returns the text content from a transcription.
func (t Transcription) Content() string { return t.Text }

/********* Specific *********/

// OpenAICompletion represents the result of a chat completion for OpenAI.
type OpenAICompletion struct {
	Message struct {
		Content string `json:"content,omitempty"`
	} `json:"message,omitempty"`
}

// AnthropicCompletion represents the result of chat completion for Anthropic.
type AnthropicCompletion struct {
	Content string `json:"text,omitempty"`
}
