name: Continuous Integration

on:
  push:
    branches: [ main, dev, dev/blog ]
  pull_request:
    branches: [ main, dev, dev/blog ]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          cache: true

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: "latest"
          args: --timeout=5m

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          cache: true

      - name: Install deps
        run: make install

      - name: Check formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -s -l .
            exit 1
          fi

      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.txt

      - name: Race detector
        run: go test -race ./...

      - name: Benchmarks
        run: go test -bench=. -benchmem ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.txt
          fail_ci_if_error: false

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          cache: true

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: './...'
